### ISSUE TITLE
관리자 공지사항 리스트 화면 + 일반유저 Navbar 구현

### ISSUE THREAD

**Issue by odukong** [UMC-Matching-Center/U.M.C_Web#25]
## Description
- Navbar 아이콘 중 pin 아이콘 클릭 시, 보여지는 공지사항 리스트 화면(notice) UI 구현
- 일반 유저(PM, User) Navbar 구현 및 Navbar 아이콘 메뉴 클릭 시 css 효과 추가(bg, bold)
- 유저 타입에 따른 Alarm content 변경

## Todo
- [x] 관리자 공지사항 리스트 화면 UI 구현
- [x] Navbar 아이콘 메뉴 클릭 시 css 속성 추가
- [x] 일반 유저(PM,User) Navbar 구현

## Etc
기타사항
