### ISSUE TITLE
로그인 전) 홈

### ISSUE THREAD

**Issue by odukong** [UMC-Matching-Center/U.M.C_Web#5]
## Description
로그인 전, 메인 홈페이지(프로젝트 리스트) 구현

## Todo
- [x] 프로젝트 리스트 화면 구현
- [x] 프로젝트 상세 화면 구현
- [x] 아이콘 하나(filter)만 이미지파일로 사용 -> filter 아이콘 삭제
- [x] 서버랑 연동하면서 무조건 수정해야하는 부분이 있는데(프로젝트 상세 페이지) 추후 수정 -> API개발 시, 수정
- [x] 스크롤 기능 -> 기능 삭제  

## Etc
기타사항
