### ISSUE TITLE
footer 및 회원가입/마이페이지 수정

### ISSUE THREAD

**Issue by hhanoo** [UMC-Matching-Center/U.M.C_Web#51]
## Description
- footer 추가 및 회원가입 및 마이페이지 디자인팀 피드백 수정

## Todo
- [x] footer 추가
- [x] 회원가입 인증 안내 문구 수정
- [x] 회원가입 드롭다운 박스 텍스트 수정
- [x] 회원가입 완료 닫기 버튼 수정
- [x] 탭 상단 제목 수정
- [x] 마이페이지 닉네임/이름 수정

## Etc
기타사항
