### ISSUE TITLE
유저 역할 별 접근 제한 기능 및 에러코드 처리 간소화, 기타 수정

### ISSUE THREAD

**Issue by hhanoo** [UMC-Matching-Center/U.M.C_Web#62]
## Description
- 유저 역할 별 접근 가능한 페이지에 따라 제한 기능 추가와 커스텀 에러 코드 처리
- 직관적이지 않던 파일명, 폴더명 변경
- 불필요한 폴더 삭제
- alert로 인한 사이트 흐름 문제 완화
- 배포에 불필요한 `console.log` 문제
- 로그인, 회원가입 페이지 글자 크기가 작은 문제
- Navbar의 알림 부분에 hover시 아무런 이벤트가 없어 다른 아이콘과 공통되지 않는 문제
- 알림 창 다른곳 클릭시 자동으로 닫히지 않아 아이콘을 재클릭 해야하는 불편함 존재

## Before
- URL을 통한 특정 페이지 강제 접근이 가능한 상태
- API 별 에러코드 차이로 인해 반복 문제점과 가독성 저하
- 페이지와 NavBar와 매칭되지 않던 파일명으로 인해 파일 탐색 난이도 상승
- 불필요한 폴더로 인해 찾은 경로 난이도 상승
- alert로 인한 사이트 흐름 중단 문제
- 배포에 불필요한 `console.log` 문제
- 로그인, 회원가입 페이지 글자 크기가 작은 문제
- Navbar의 알림 부분에 hover시 아무런 이벤트가 없어 다른 아이콘과 공통되지 않는 문제
- 알림 창 다른곳 클릭시 자동으로 닫히지 않던 문제

## After
- 역할에 따른 URL 접근 제한으로 인해 서버 오류 반환 빈도 감수
- 에러코드 메시지 일괄 처리를 통해 가독성 상승 및 API 관리 난이도 하락
- 페이지의 기능과 직관되는 파일명 변경으로 파일 탐색 난이도 완화
- 불필요한 폴더를 삭제하여 파일 경로 난이도 하락
- 기존 alert 대신 toast로 대채하여 사이트 흐름 문제 완화
- 배포에 불필요한 `console.log` 삭제
- 로그인, 회원가입 페이지 글자 크기를 키워서 가독성 증가
- Navbar의 알림 부분에 hover시 다른 아이콘과 같은 효과를 넣어 다른 아이콘과 공통화
- 알림 창 다른곳 클릭시 자동으로 닫히도록 수정

## Todo
- [x] 유저 역할별 접근 가능 페이지 기능 추가
- [x] 에러 코드 메시지 일괄 처리
- [x] 직관적이지 않은 파일명 변경
- [x] 사이트 흐름을 방해하는 alert 대신 toast로 변경
- [x] consolo.log 삭제
- [x] 로그인, 회원가입 페이지 글자 크기 2px씩 증가
- [x] Navbar의 알림 부분에 hover 효과 추가
- [x] 알림 창 다른곳 클릭시 자동으로 닫기 기능 추가
